# Base configuration
baseURL = 'https://aimadahsan.github.io/blog'
languageCode = 'en-us'
title = '~/blog'

# Set the theme
theme = 'flux'

# Set copyright details
copyright = "Aimad Ahsan"

[taxonomies]
   tag = "tags"
   category = "categories"

#
# Navigation Menus
#

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'home'
  url = '/'
  weight = -110
[[menu.main]]
  identifier = 'about'
  name = 'about'
  url = '/about'
  weight = -100
[[menu.main]]
  identifier = 'categories'
  name = 'categories'
  url = '/categories'
  weight = 100
[[menu.main]]
  identifier = 'tags'
  name = 'tags'
  url = '/tags'
  weight = 110

#
# Theme Params - Color Scheme + Social Media Links
#

[params]
  
  colortheme = "classic"
  
  [[params.social]]
    name = "github"
    link = "https://github.com/imxdn"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/aimadahsan/"

  [[params.social]]
    name = "keybase"
    link = "https://keybase.io/imxdn"

  [[params.social]]
    name = "email"
    link = "ahsanaimad@gmail.com?subject=Email from blog" # no need for "mailto:" at the start